apiVersion: apps/v1
kind: Deployment
metadata:
  name: jobportal

spec:
  replicas: 3
  selector:
    matchLabels:
      app: jobportal
  template:
    metadata:
      labels:
        app: jobportal

    spec:
      containers:
        - name: jobportal-container
          image: uk.icr.io/ibm_assignments/jobportal
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
              protocol: TCP